version: '3.7'
services:
  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  api_back:
    build: ./ecfback
    container_name: springlocalib
    restart: always
    depends_on:
      - mongo_db
    ports:
      - 8080:8080
#   api_front:
#     build: ./EFC_CDA_Localib
#     container_name: angularlocalib
#     depends_on:
#       - api_back
#     ports:
#       - 4200:4200

# version: '3.7'

# services:
#   localib:
#     container_name: localib-container
#     build: 
#     ports:
#       - 8080:8080